name: 'AWS EKS deploy workflow'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-backend:
    name: 'Create the remote backend for Terraform job'
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region:  ${{ vars.AWS_REGION }}

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version

    - name: Copy variables file
      run: |
        cd aws/mario
        cp -fr terraform.tfvars ../backend/terraform.tfvars

    - name: Create remote backend
      run: |
        cd aws/backend
        terraform init
        terraform apply -auto-approve
        if [[ $(terraform output -raw bucket) == "" ]]; then
          echo "Remote backend was not created! Exiting script..."
          exit 1
        fi
    
#    - name: Upload backend.tf as artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: backend-artifact
#        path: aws/mario/backend.tf
#        overwrite: true

    - name: Save backend.tf to cache
      uses: actions/cache/save@v4
      with:
        path: aws/mario/backend.tf
        key: backend.tf-key


  terraform-cluster:
    name: 'Create the cluster resources with Terraform job'
    runs-on: ubuntu-latest
    environment: aws
    needs: terraform-backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
#    - name: Download backend.tf
#      uses: actions/download-artifact@v4
#      with:
#        name: backend-artifact
#        path: aws/mario

    - name: Restore cached backend.tf
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: aws/mario/backend.tf
        key: backend.tf-key
        fail-on-cache-miss: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region:  ${{ vars.AWS_REGION }}

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version

    - name: Terraform apply to create the cluster resources
      run: |
        cd aws/mario
        echo "$PWD"
        terraform init
        terraform apply -auto-approve


  kubectl:
    name: 'Configure the cluster with kubectl job'
    runs-on: ubuntu-latest
    environment: aws
    needs: terraform-cluster
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region:  ${{ vars.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks --region ${{ vars.AWS_REGION }} update-kubeconfig --name ${{ vars.PROJECT_NAME }}-cluster

    - name: Deploy to Kubernetes
      run: |
        cd aws/mario
        echo "$PWD"
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get all
        kubectl describe service mario-service
        echo "Waiting for the external hostname of the LoadBalancer to become available..."
        # kubectl wait --for=jsonpath='{.status.loadBalancer.ingress[0].hostname}' service/mario-service --timeout=300s
        echo "Open this URL in your favorite browser: http://$(kubectl get service mario-service -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
