name: 'AWS EKS destroy workflow'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-cluster:
    name: 'Destroy the cluster resources with Terraform job'
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore cached backend.tf
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: aws/mario/backend.tf
        key: backend.tf-key
        fail-on-cache-miss: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region:  ${{ vars.AWS_REGION }}

    - name: Install Terraform
      run: |
        terraform version
#       curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
#        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
#        sudo apt-get update
#        sudo apt-get install -y terraform
#        terraform version

    - name: Terraform destroy the cluster resources
      run: |
        cd aws/mario
        echo "$PWD"
#        terraform init
#        terraform destroy --auto-approve

    - name: Extract values from backend.tf
      id: extract
      run: |
        cd aws/mario
        echo "$PWD"
        BUCKET_NAME=$(grep -oP '(?<=bucket\s+=\s+")[^"]+' backend.tf)-$(grep -oP '(?<=region\s+=\s+")[^"]+' backend.tf)
        DYNAMODB_TABLE=$(grep -oP '(?<=dynamodb_table\s+=\s+")[^"]+' backend.tf)
        echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "dynamodb_table=$DYNAMODB_TABLE" >> $GITHUB_OUTPUT
          
    - name: Clean up the backend resources
      run: |
        aws iam list-attached-role-policies --role-name terraform-backend-role --query "AttachedPolicies[].PolicyArn" --output text | tr '\t' '\n' | xargs -I {} aws iam detach-role-policy --role-name terraform-backend-role --policy-arn {}
        aws iam delete-role --role-name terraform-backend-role
        aws dynamodb delete-table --table-name ${{ steps.extract.outputs.dynamodb_table }}
        aws s3 rm s3://${{ steps.extract.outputs.bucket_name }} --recursive
        aws s3api delete-objects --bucket  ${{ steps.extract.outputs.bucket_name }} --delete "$(aws s3api list-object-versions --bucket ${{ steps.extract.outputs.bucket_name }} --output=json --query='{Objects: Versions[].{Key:Key,VersionId:VersionId}}')"
        aws s3 rb s3://${{ steps.extract.outputs.bucket_name }} --force