name: 'AWS EKS destroy workflow'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-cluster:
    name: 'Destroy the cluster resources with Terraform job'
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore cached backend.tf
      uses: actions/cache/restore@v4
      id: restore-cache
      with:
        path: aws/mario/backend.tf
        key: backend.tf-key
        fail-on-cache-miss: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
        aws-region:  ${{ vars.AWS_REGION }}

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version

    - name: Terraform destroy the cluster resources
      run: |
        cd aws/mario
        echo "$PWD"
        terraform init
        terraform destroy --auto-approve
