name: 'AWS EKS workflow'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  aws:
    name: 'AWS EKS deployment job'
    runs-on: ubuntu-latest
    environment:
      name: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #aws-region: your-aws-region

    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version

    - name: Copy variables file
      run: |
        cd aws/mario
        cp -fr terraform.tfvars ../backend/terraform.tfvars

    - name: Create remote backend
      run: |
        cd aws/backend
        terraform init
        terraform apply -auto-approve
        if [[ $(terraform output -raw bucket) == "" ]]; then
          echo "Remote backend was not created! Exiting script..."
          exit 1
        fi

    - name: Create Kubernetes cluster
      run: |
        cd aws/mario
        echo "$PWD"
        terraform init
        terraform apply -auto-approve

    - name: Install kubectl
      run: |
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get install -y kubectl
        kubectl version --client

    - name: Update kubeconfig
      run: |
        aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get all
        kubectl describe service mario-service
        echo "Waiting for the external hostname of the LoadBalancer to become available..."
        # kubectl wait --for=jsonpath='{.status.loadBalancer.ingress[0].hostname}' service/mario-service --timeout=300s
        echo "Open this URL in your favorite browser: http://$(kubectl get service mario-service -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}')"
